# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(2, 'Left Bottom'), (4, 'Right Top'), (3, 'Center'), (1, 'Left Top'), (5, 'Right Bottom')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Post')),
            ],
        ),
    ]
