# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_homepageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title', unique=True),
            preserve_default=False,
        ),
    ]
