# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Post', unique=True),
        ),
    ]
