# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20190318_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageview',
            name='position',
            field=models.IntegerField(choices=[(2, 'Left Bottom'), (4, 'Right Top'), (3, 'Center'), (1, 'Left Top'), (5, 'Right Bottom')], unique=True),
        ),
        migrations.AlterField(
            model_name='homepageview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Post'),
        ),
    ]
