# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_auto_20190325_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_screen',
            field=models.BooleanField(default=False),
        ),
    ]
