# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_advertupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandScape1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload image with dimension 728 x 90', upload_to='advert')),
            ],
        ),
        migrations.CreateModel(
            name='LandScape2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload image with dimension 728 x 90', upload_to='advert')),
            ],
        ),
        migrations.CreateModel(
            name='LandScape3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload image with dimension 728 x 90', upload_to='advert')),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload image with dimension 250 x 250', upload_to='advert')),
            ],
        ),
        migrations.DeleteModel(
            name='AdvertUpload',
        ),
    ]
